version: "3.3"

services:
  website:
    container_name: php7.4-apache
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=mypassword
      #- MYSQL_DBNAME=
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    restart: always
    volumes:
      - /mnt/shared:/mnt/shared
    networks:
      customnetwork:
        ipv4_address: 192.168.100.100

  mysql:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      #MYSQL_DATABASE: ohif # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    networks:
      customnetwork:
        ipv4_address: 192.168.100.101

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: mypassword #(Required) set the password for the root superuser account.
      PMA_HOST: mysql   # define the address/hostname of the mysql server eg mysql container name.
      #PMA_USER: root # this is the root user to login on startup
      #PMA_PASSWORD: mypassword # use the root password to login on startup.
      # Create a new user on startup (optional)
      # MYSQL_USER: newuser
      # MYSQL_PASSWORD: mypassword
    restart: always
    networks:
      customnetwork:
        ipv4_address: 192.168.100.102

volumes: 
  my-db:

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 192.168.100.1/16
